### ISSUE TITLE
realtime-stream.ipynb problem

### ISSUE THREAD

**Issue by zhangji-hhu** [influxdata/influxdb-client-python#139]
when i use the realtime-stream.ipynb, the error "TypeError: Streaming DataFrame expects an example of DataFrame like objects. Got: Empty DataFrame" was reported.  May I ask what the problem is?

**Comment by bednar** [comment]
Hi @zhangji-hhu,

thanks for using our client.

The problem is caused by incompatibility of https://github.com/python-streamz/streamz/issues/346 and [pandas.DataFrame v1.1](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.value_counts.html). As a workaround you could use pandas v 1.0.5:

```
pip install --upgrade pandas==1.0.5
```

Regards

**Comment by zhangji-hhu** [comment]
thank you!
