### ISSUE TITLE
BucketsApi.create_bucket fails if org_id is not being passed to it

### ISSUE THREAD

**Issue by asherf** [influxdata/influxdb-client-python#197]
If an org_id is not passed to the BucketsApi.create_bucket call, then the logic in the method tries to get the org id from the InfluxDBClient class.
However, InfluxDBClient.org seem to be the an org name.
There is no check in the InfluxDBClient init function,, but since the param name is `org` and not `org_id` it seems that the API expects the org name in that param. Further more, the examples in the docs pass an org name to that param.

<img width="737" alt="Screen Shot 2021-02-21 at 7 13 06 PM" src="https://user-images.githubusercontent.com/1268088/108652384-d5fda700-7478-11eb-885b-781c07170110.png">

The bug is here: https://github.com/influxdata/influxdb-client-python/blob/d396581287e263719dec749227a02921417063fb/influxdb_client/client/bucket_api.py#L49

I am happy to contribute a fix here, but since I am new to influxdb, some guidance as to the preferred solution would be appreciated.

There are two possible solutions I can think of:
1. Allow passing an org_id to the InfluxDBClient init and keep it on the instance, since this would be useful when calling other APIs that take an org id
2. Make the org_id param mandatory for the create_bucket api and raise an exception if it is not being passed to that method.

I am happy to implement either of those based on guidance from maintainers of this package.

**Comment by bednar** [comment]
Hi @asherf,

thanks for using our client and your offer 👍.

The problem is caused by different behaviour of InfluxDB API. The `Write` and `Query` API takes `org` interchangeably - either the `ID` or `Name` could be specified. In the opposite the `Bucket` API needs to have specified the `ID`.

- https://docs.influxdata.com/influxdb/cloud/api/#tag/Write
- https://docs.influxdata.com/influxdb/cloud/api/#operation/PostQuery
- https://docs.influxdata.com/influxdb/cloud/api/#operation/PostBuckets

I think the ideal solution will be validate that the `self._influxdb_client.org` is valid ID in `bucket_api.py`.

- https://github.com/influxdata/influxdb/blob/master/id.go
- https://github.com/influxdata/influxdb/blob/master/id_test.go

What do you think?

Regards

**Comment by asherf** [comment]
I agree, I'll have a PR later this week.
Having said that... I think it is worth while to make the influxdb API more consistent, i.e. accept org id/name everywhere not just in a subset of endpoints

**Comment by bednar** [comment]
> I agree, I'll have a PR later this week.

Great news 👍 ... every PR is welcome... Thanks for that

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
