### ISSUE TITLE
Split requests for max-body-size

### ISSUE THREAD

**Issue by max-soe** [influxdata/influxdb-client-python#392]
__Proposal:__
You can specify the max body size of the influxdb and the client split the data points into correct batches.

__Current behavior:__
If you try to sent a bigger batch of datapoints with
``` client.write_points(points)```. 

You get the error message: 

```influxdb.exceptions.InfluxDBClientError: 413: <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.17.4</center>
</body>
</html>
```
This already happen if the plain data points only have 1.500.000 bytes.

__Desired behavior:__
The client check the size of the body and split the data into different requests if necessary.

__Use case:__
We are not the owner of the influxdb instance and can not change the max-body-size.
But it's also hard to calculate the bytes of the body, because the body is created in this library.
Further the byte size of our data points are very different.
So it's very hard to find a good batch size for all our datapoints.

**Comment by bednar** [comment]
Hi @max-soe,

thanks for your proposal.

Is this something you might be willing to help with?

Regards

**Comment by bednar** [comment]
Hi @max-soe,

Currently We don't want to include this in our library because it is not that common. I've prepared the following example to show you how to achieve the required functionality by `RxPy`:

https://github.com/influxdata/influxdb-client-python/blob/8c8ab279cfdb86d232cbc7953b63bd64acd9094b/examples/write_batching_by_bytes_count.py#L83

Regards
