### ISSUE TITLE
Numpy dependency breaks AWS Lambda functions

### ISSUE THREAD

**Issue by DrBomb** [influxdata/influxdb-client-python#43]
I'm trying to deploy this API to a lambda function. And there two issues with having numpy as a dependency:

- Increases the package size to almost 41Mb
- AWS lambda environments are not compatible with NumPy per https://github.com/numpy/numpy/issues/13465

It would be great to have a lite API that can work without them as dependencies.

**Comment by semyont** [comment]
Same here, working on serverless with aws
  **An error occurred: xyzLambdaFunction - Unzipped size must be smaller than 262144000 bytes (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: xxx).**
this  becomes very bloated (41 mb ) because of pandas requirement, is there any reason why this package should be included in a lean swagger generated client?

**Comment by bednar** [comment]
Hi @DrBomb, @semyont 

We support querying into Pandas DataFrame for using in data analysis - something like - [stock-predictions.ipynb](https://github.com/influxdata/influxdb-client-python/blob/master/notebooks/stock-predictions.ipynb), but we will change the pandas depency to optional as is in old client.

Regards

**Comment by semyont** [comment]
Hi @bednar thank you for the quick response, when should we expect a release?

**Comment by bednar** [comment]
Milestone [1.2.0](https://github.com/influxdata/influxdb-client-python/milestone/4) is planned at 2019-12-06.

**Comment by bednar** [comment]
Hi @semyont, @DrBomb 

The issue is fixed in [1.2.0 milestone](https://github.com/influxdata/influxdb-client-python/milestone/4). 

If you would like to use a dev version install client via:

```pip install git+https://github.com/influxdata/influxdb-client-python.git@master```

Regards
