### ISSUE TITLE
warnings returned when using example program on https://influxdb-client.readthedocs.io/en/latest/

### ISSUE THREAD

**Issue by schaefer01** [influxdata/influxdb-client-python#633]
### Specifications

* Client Version: '1.39.0'
* InfluxDB Version: v2.7.4 
* Platform:  20.04.6 LTS

### Code sample to reproduce problem

```python
```
see https://influxdb-client.readthedocs.io/en/latest/  at "Getting Started"

### Expected behavior

I expected no warnings

### Actual behavior

/home/ubuntu/radioconda/lib/python3.10/site-packages/influxdb_client/client/flux_csv_parser.py:334: UserWarning: The response contains columns with duplicated names: '['', 'result', 'table', '_start', '_stop', '_time', '_value', '_field', '_measurement', 'org', 'result']'.

You should use the 'record.row' to access your data instead of 'record.values' dictionary.

  warnings.warn(message, UserWarning)
The response contains columns with duplicated names: '['', 'result', 'table', '_start', '_stop', '_time', '_value', '_field', '_measurement', 'org', 'result']'.

You should use the 'record.row' to access your data instead of 'record.values' dictionary

**Comment by bednar** [comment]
Hi @schaefer01,

Thank you for bringing this to our attention. Based on your description, it sounds like the warning you're encountering is specific to the profile query example provided in our documentation.

In this instance, since the warning is confined to an example scenario and does not impact actual functionality or performance, my recommendation would be to ignore it. 

However, if you find that this warning is appearing in other contexts or affecting your usage of the client, please let us know so we can investigate further.

Regards.

**Comment by reidprichard** [comment]
I'm getting this exact error while using https://github.com/maxlyth/influxv2tovm to migrate InfluxDBv2 to VictoriaMetrics.
```
.../flux_csv_parser.py:348: UserWarning: The response contains columns with duplicated names: '['', 'result', 'table', '_start', '_stop', '_time', '_value', '_field', '_measurement', 'result']'.

You should use the 'record.row' to access your data instead of 'record.values' dictionary.
```

Very much a script kiddie when it comes to database stuff so I wasn't able to do much troubleshooting myself, but I'd be happy to help with a bit of guidance.
