### ISSUE TITLE
Multiprocessing: Serialization with Pickle

### ISSUE THREAD

**Issue by JSchnepp** [influxdata/influxdb-client-python#69]
Hi all,

I find it interesting that so far no one has a problem with serialization in multiprocessing using Pickle. After initialization in the following lines

       "" "
      Start writer as a new process
      "" "
     writer = InfluxDBWriter (queue_)

"writer" is started

     writer.start ()

and InfluxDBWriter must be serialized for pipe transfer. The following error message occurs:

File "/Users/joerg/miniconda3/envs/influx/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
     ForkingPickler (file, protocol) .dump (obj)
AttributeError: Can't pickle local object 'PoolManager .__ init__. <locals>. <lambda>'

This error is triggered by the line >>>>:
     def __init __ (self, queue):
         Process .__ init __ (self)
         self.queue = queue
   >>>> self.client = InfluxDBClient (url = 'http: // localhost: 9999',
                token = "my_token", org = "my_org", debug = False)

Hardware: MacBook Pro, OS: Catalina
Python: 3.8.1
pypi: 2.1
influxdb-client: 1.4.0

**Comment by bednar** [comment]
Hi @JSchnepp,

Thanks for reporting a problem.

It's probably caused by not serializing: https://github.com/influxdata/influxdb-client-python/blob/ce818996418901e9f768d4b7e656a1e993059a3e/influxdb_client/rest.py#L97 on https://github.com/influxdata/influxdb-client-python/blob/ce818996418901e9f768d4b7e656a1e993059a3e/influxdb_client/rest.py#L35

We will fix it asap.

Regards

**Comment by bednar** [comment]
Hi @JSchnepp,

I prepared fixed version in a branch `fix/pickle`.

If you would like to test it then install client via:

```pip install git+https://github.com/influxdata/influxdb-client-python.git@fix/pickle```

Regards
