### ISSUE TITLE
more verbosity 

### ISSUE THREAD

**Issue by macd2** [influxdata/influxdb-client-python#95]
When writing lines with client.write() than many times I do not get any output (function returns None) but the line was not written to influx and have no clue why. So is there a way to get some more info about the result of the action?

**Comment by bednar** [comment]
Hi @macd2,

`client.write()` returns `None` because the default strategy for write is [batching](https://github.com/influxdata/influxdb-client-python#batching). If you would like to directly write data use [synchronous strategy](https://github.com/influxdata/influxdb-client-python#synchronous-client):

```python
from influxdb_client import InfluxDBClient, Point
from influxdb_client .client.write_api import SYNCHRONOUS

client = InfluxDBClient(url="http://localhost:9999", token="my-token", org="my-org")
write_api = client.write_api(write_options=SYNCHRONOUS)

_point1 = Point("my_measurement").tag("location", "Prague").field("temperature", 25.3)
_point2 = Point("my_measurement").tag("location", "New York").field("temperature", 24.3)

write_api.write(bucket="my-bucket", record=[_point1, _point2])

client.__del__()
```

The client could be configured to debug verbosity by:

```python
client = InfluxDBClient(url="http://localhost:9999", token="my-token", org="my-org", debug=True)
```


Regards

**Comment by macd2** [comment]
thank you very much this solves my issue!

**Comment by bednar** [comment]
You are welcome
